language: java
matrix:
  include:
    ## kept in sync with javafx-maven-plugin for easier comparision
    ## https://docs.travis-ci.com/user/reference/trusty/
    - os: linux
      sudo: false
      dist: trusty
      jdk: oraclejdk8
      install: true
      env: FAILURES_ALLOWED=false
      addons:
        apt:
          packages:
          ## RPM
            - rpm
          ## DEB
            - fakeroot
    ## OpenJDK should work too, but TravisCI has no up2date Ubuntu-Image, makes it impossible to install OpenJFX
    - os: linux
      sudo: false
      dist: trusty
      jdk: oraclejdk9
      install: true
      env: FAILURES_ALLOWED=false
      addons:
        apt:
          packages:
          ## RPM
            - rpm
          ## DEB
            - fakeroot
    ## has older Maven
    - os: linux
      sudo: false
      dist: precise
      jdk: oraclejdk8
      env: FAILURES_ALLOWED=false
      addons:
        apt:
          packages:
          ## RPM
            - rpm
          ## DEB
            - fakeroot
    ## use different OSX versions
    ## OS X 10.11
    - os: osx
      osx_image: xcode8
      env: FAILURES_ALLOWED=false
    ## OS X 10.12
    - os: osx
      osx_image: xcode8.3
      env: FAILURES_ALLOWED=false
    ## OS X 10.12
    - os: osx
      osx_image: xcode9.2
      env: FAILURES_ALLOWED=false
  allow_failures:
    - env: FAILURES_ALLOWED=true

# http://stackoverflow.com/questions/35128777/travis-ci-build-failed#comment58070003_35153221
before_install:


script:
  - cd tagfinderui
  - chmod +x gradlew
  - ./gradlew jfxnative
  - cd build/jfx/native/
  - ls
before_deploy:
      # Set up git user name and tag this commit
      - git config --local user.name "mkpchiran"
      - git config --local user.email "mkpchiran@gmail.com"
      - git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"
deploy:
  provider: releases
  api_key: 5737543c12610b9f399f6a2a09737f7718db055c
  file: build/jfx/native/**/*
  skip_cleanup: true
  on:
    repo: mkpchiran/UniversalTagFinder
    tags: true
    branch: master
    all_branches: true	


